apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: projecthub-frontend-ingress
  namespace: projecthub-frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: projecthub.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: projecthub-frontend-service
            port:
              number: 80
